services:
  app:
    container_name: apache
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ./app/html/
        target: /var/www/html/
    networks:
      - webapp-network
    depends_on:
      - db

  db:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql/
      - type: bind
        source: ./db/init/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    networks:
      - webapp-network

volumes:
  mysql-data:
    name: mysql-data

networks:
  webapp-network:
    driver: bridge
    name: webapp-network